
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Augusto Winkler\Desktop\teste\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("753x526")
window.configure(bg = "#343434")


canvas = Canvas(
    window,
    bg = "#343434",
    height = 526,
    width = 753,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    163.0,
    11.0,
    anchor="nw",
    text="Calculadora Laser CNC",
    fill="#C9C6B9",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    198.0,
    490.0,
    anchor="nw",
    text="Criado e Desenvolvido por: Augusto Winkler.",
    fill="#C9C6B9",
    font=("Inter", 12 * -1)
)
window.resizable(False, False)
window.mainloop()
