
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Augusto Winkler\Desktop\teste\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("347x226")
window.configure(bg = "#262626")


canvas = Canvas(
    window,
    bg = "#262626",
    height = 226,
    width = 347,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    173.0,
    23.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=33.0,
    y=14.0,
    width=280.0,
    height=16.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    244.5,
    85.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=176.0,
    y=76.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    35.0,
    78.0,
    anchor="nw",
    text="Valor Máquina:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    244.5,
    112.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=176.0,
    y=103.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    35.0,
    105.0,
    anchor="nw",
    text="Vida Util:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    243.5,
    141.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=175.0,
    y=132.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    34.0,
    134.0,
    anchor="nw",
    text="Valor Residual:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    243.5,
    181.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=175.0,
    y=172.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    34.0,
    174.0,
    anchor="nw",
    text="Valor Laser:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    243.5,
    208.0,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=175.0,
    y=199.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    34.0,
    201.0,
    anchor="nw",
    text="Vida Util:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=33.0,
    y=42.0,
    width=128.0,
    height=24.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=185.0,
    y=41.0,
    width=128.0,
    height=24.0
)

canvas.create_rectangle(
    -3.0,
    160.0,
    347.0,
    163.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
