
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Augusto Winkler\Desktop\teste\assets\frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("347x161")
window.configure(bg = "#262626")


canvas = Canvas(
    window,
    bg = "#262626",
    height = 161,
    width = 347,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    244.5,
    39.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=176.0,
    y=30.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    35.0,
    32.0,
    anchor="nw",
    text="Hora Máquina:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    244.5,
    66.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=176.0,
    y=57.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    35.0,
    59.0,
    anchor="nw",
    text="Minuto Máquina:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    243.5,
    95.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=175.0,
    y=86.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    34.0,
    88.0,
    anchor="nw",
    text="Lucro Estimado:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    243.5,
    122.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=175.0,
    y=113.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    34.0,
    115.0,
    anchor="nw",
    text="Valor Total:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)
window.resizable(False, False)
window.mainloop()
